//@GeneratedCode
namespace SEBookStore.MVVMApp.Models
{
    using System;
    /// <summary>
    /// This model represents a transmission model for the 'Book' data unit.
    /// </summary>

    public partial class Book : SEBookStore.Common.Contracts.IBook
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static Book()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="Book"/> class (created by the generator.)
        /// </summary>
        public Book()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called the object is being constraucted.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'ISBNNumber' generated by the generator.
        /// </summary>
        public System.String ISBNNumber { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Author' generated by the generator.
        /// </summary>
        public System.String Author { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Description' generated by the generator.
        /// </summary>
        public System.String Description { get; set; } = string.Empty;
        /// <summary>
        /// Property 'YearOfRelease' generated by the generator.
        /// </summary>
        public System.Int32 YearOfRelease { get; set; }
        /// <summary>
        /// Property 'Price' generated by the generator.
        /// </summary>
        public System.Double Price { get; set; }
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        /// <param name="obj">The object to compare with the current object.</param>
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Book other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        /// <summary>
        /// Serves as the default hash function.
        /// </summary>
        public override int GetHashCode()
        {
            return this.CalculateHashCode(ISBNNumber, Author, Title, Description, YearOfRelease, Price, Id);
        }
    }
}
