//@GeneratedCode
namespace SEBookStore.Logic.Entities
{
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    partial class Book : SEBookStore.Common.Contracts.IBook
    {
    }
}
