//@GeneratedCode
namespace SEBookStore.Logic.Contracts
{
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial interface IBookSet : IEntitySet<Entities.Book>
    {
    }
}
