//@GeneratedCode
namespace SEBookStore.Logic.Contracts
{
    /// <summary>
    /// Generated by the generator
    /// </summary>
    partial interface IContext
    {
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        IEntitySet<Entities.Book> BookSet { get; }
    }
}
