//@Customized
namespace SEBookStore.MVVMApp.ViewModels
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class BooksViewModel : GenericItemsViewModel<Models.Book>
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static BooksViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="BooksViewModel"/> class (created by the generator.)
        /// </summary>
        public BooksViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called the object is being constraucted.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructed();
        protected override Avalonia.Controls.Window CreateWindow()
        {
            throw new NotImplementedException();
        }
        protected override GenericItemViewModel<Models.Book> CreateViewModel()
        {
            throw new NotImplementedException();
        }
    }
}
