//@GeneratedCode
namespace SEBookStore.Logic.DataContext
{
    /// <summary>
    /// Generated by the generator
    /// </summary>
    partial class ProjectDbContext
    {
        #region properties
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.Book> DbBookSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.IEntitySet<Entities.Book> BookSet => GetEntitySet<Entities.Book>();
        #endregion properties

        #region partial methods
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.EntityObject
        {
            if (typeof(E) == typeof(Entities.Book))
            {
                dbSet = DbBookSet as DbSet<E>;
                handled = true;
            }
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorEntitySet<E>(ref EntitySet<E>? entitySet, ref bool handled) where E : Entities.EntityObject, new()
        {
            if (typeof(E) == typeof(Entities.Book))
            {
                entitySet = new DataContext.BookSet(this, DbBookSet) as EntitySet<E>;
                handled = true;
            }
        }
        #endregion partial methods
    }
}
