//@GeneratedCode
@startuml SEBookStore.Logic.Entities.Book
+class Book #whitesmoke {
    - String iSBNNumber
    - String _author
    - String _title
    - String _description
    - Int32 _yearOfRelease
    - Double _price
    ---
     + String getISBNNumber()
     + setISBNNumber(String value)
     + String getAuthor()
     + setAuthor(String value)
     + String getTitle()
     + setTitle(String value)
     + String getDescription()
     + setDescription(String value)
     + Int32 getYearOfRelease()
     + setYearOfRelease(Int32 value)
     + Double getPrice()
     + setPrice(Double value)
    ---
    + {static}Boolean CheckISBNNumer(String number)
    ---
    + String get_ISBNNumber()
    + Void set_ISBNNumber(String value)
    + String get_Author()
    + Void set_Author(String value)
    + String get_Title()
    + Void set_Title(String value)
    + String get_Description()
    + Void set_Description(String value)
    + Int32 get_YearOfRelease()
    + Void set_YearOfRelease(Int32 value)
    + Double get_Price()
    + Void set_Price(Double value)
    + String ToString()
    + Void Validate(IContext context)
}
+abstract class EntityObject #white {
    - Int32 _id
    ---
     + Int32 getId()
     + setId(Int32 value)
    ---
    + Int32 get_Id()
    + Void set_Id(Int32 value)
}
interface IValidatableEntity #lightgrey {
    + Void Validate(IContext context)
}
interface IIdentifiable #lightgrey {
     + Int32 getId()
     + setId(Int32 value)
    ---
    + Int32 get_Id()
    + Void set_Id(Int32 value)
}
EntityObject <|-- Book
IValidatableEntity ()- Book
IIdentifiable ()- EntityObject
@enduml
